/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.fornecedor;

import controller.ControllerFornecedor;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import model.GestaoFornecedor;

/**
 *
 * @author vinny
 */
public class TelaFornecedor extends javax.swing.JFrame {
    ControllerFornecedor cf;
    DefaultListModel dfNome;
    DefaultListModel dfCNPJ;
    ArrayList<GestaoFornecedor> fornecedores;    

    /**
     * Creates new form TelaFornecedor
     */
    public TelaFornecedor() throws SQLException {
        initComponents();
        cf = new ControllerFornecedor();
      fornecedores =  cf.getAll();
      dfNome= new DefaultListModel();
      dfCNPJ = new DefaultListModel();
      for(int i = 0 ; i < fornecedores.size();i++){
       dfNome.addElement(fornecedores.get(i).getNome());
       dfCNPJ.addElement(fornecedores.get(i).getCnpj());
      
      }
      jListNome.setModel(dfNome);
      jListCNPJ.setModel(dfCNPJ);
  
        
       
    }
    public void habilitaBotaoRemover(){
     if(jListCNPJ.isSelectionEmpty()){
     jButtonRemover.setEnabled(true);
         System.out.println("aqui2");
     }
     if(jListNome.isSelectionEmpty()){
     jButtonRemover.enable(true);
     }
        
    }
    
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldBuscaFornecedor = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();
        jButtonRemover = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonAdicionar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListNome = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListCNPJ = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxSelecionarBusca = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonBuscar.setText("buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jButtonRemover.setText("remover");
        jButtonRemover.setEnabled(false);
        jButtonRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoverActionPerformed(evt);
            }
        });

        jButton3.setText("editar");
        jButton3.setEnabled(false);

        jLabel1.setText("Fornecedor");

        jButtonAdicionar.setText("adicionar");
        jButtonAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setText("FORNECEDOR");

        jListNome.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListNomeValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jListNome);

        jListCNPJ.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListCNPJValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(jListCNPJ);

        jLabel3.setText("NOME");

        jLabel4.setText("CNPJ");

        jComboBoxSelecionarBusca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nome", "CNPJ" }));
        jComboBoxSelecionarBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSelecionarBuscaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldBuscaFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(56, 56, 56))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxSelecionarBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonAdicionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonRemover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(106, 106, 106))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldBuscaFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxSelecionarBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jButtonAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3)))))
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
          boolean encontrou = false;
        if(jTextFieldBuscaFornecedor.getText().length() == 14){
            if(jComboBoxSelecionarBusca.getSelectedItem().equals("CNPJ")) {
            if(jTextFieldBuscaFornecedor.getText().length() == 14){
            
            } 
            
              for (int i = 0; i < fornecedores.size() && !encontrou; i++) {
                if (jTextFieldBuscaFornecedor.getText().equals(fornecedores.get(i).getCnpj())) {
                 
                    jListNome.setSelectedValue(fornecedores.get(i).getNome(), true);
                    encontrou = true;
                }
            }
            try{  
             Long.parseLong(jTextFieldBuscaFornecedor.getText());
            jListCNPJ.setSelectedValue(jTextFieldBuscaFornecedor.getText(), true);
                         if(!encontrou){
                 JOptionPane.showMessageDialog(null, "Fornecedor não encontrado");
                    jListCNPJ.setSelectedIndex(0);
                    jListNome.setSelectedIndex(0);
 
            }
            }
           catch(Exception e){
             JOptionPane.showMessageDialog(null, "CNPJ Inválido");
                }

        }
      
        if (jComboBoxSelecionarBusca.getSelectedItem().equals("Nome")) {
            jListNome.setSelectedValue(jTextFieldBuscaFornecedor.getText(), true);
         
            for (int i = 0; i < fornecedores.size() && !encontrou; i++){
               
             
                if(jTextFieldBuscaFornecedor.getText().equals(fornecedores.get(i).getNome())) {
                    jListCNPJ.setSelectedValue(fornecedores.get(i).getCnpj(), true);
                    encontrou=true;
                }
            }
            
            if(!encontrou){
                jListCNPJ.setSelectedIndex(0);
                jListNome.setSelectedIndex(0);
                                  
                 JOptionPane.showMessageDialog(null, "Fornecedor não encontrado");

            }
            


            
        } 

        }

    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoverActionPerformed
//    String nome = jList1.getSelectedValue();
//        try {
//            new ControllerFornecedor().deletar(nome);
//            list.removeElement(nome);
//        } catch (SQLException ex) {
//            System.out.println("Erro");
//        }
//        
        
// TODO add your handling code here:
    }//GEN-LAST:event_jButtonRemoverActionPerformed

    private void jButtonAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarActionPerformed
        new TelaFormFornecedor().setVisible(true);
        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAdicionarActionPerformed

    private void jComboBoxSelecionarBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSelecionarBuscaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxSelecionarBuscaActionPerformed

    private void jListCNPJValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListCNPJValueChanged
        // TODO add your handling code here:
        boolean encontrou = false;
        jButtonRemover.setEnabled(true);
        for(int i = 0 ; i<fornecedores.size() && !encontrou;i++){
            if(jListCNPJ.getSelectedValue().equals(fornecedores.get(i).getCnpj())){
              jListNome.setSelectedValue(fornecedores.get(i).getNome(), true);
              encontrou=true;
            }
        }
   
        
    }//GEN-LAST:event_jListCNPJValueChanged

    private void jListNomeValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListNomeValueChanged
        // TODO add your handling code here:
          boolean encontrou = false;
        jButtonRemover.setEnabled(true);
        for(int i = 0 ; i<fornecedores.size() && !encontrou;i++){
            if(jListNome.getSelectedValue().equals(fornecedores.get(i).getNome())){
              jListCNPJ.setSelectedValue(fornecedores.get(i).getCnpj(), true);
              encontrou=true;
            }
        }
   
        
    }//GEN-LAST:event_jListNomeValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new TelaFornecedor().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(TelaFornecedor.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonAdicionar;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonRemover;
    private javax.swing.JComboBox<String> jComboBoxSelecionarBusca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<String> jListCNPJ;
    private javax.swing.JList<String> jListNome;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextFieldBuscaFornecedor;
    // End of variables declaration//GEN-END:variables
}
