/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.main;

import com.qoppa.pdfWriter.PDFDocument;
import com.qoppa.pdfWriter.PDFGraphics;
import com.qoppa.pdfWriter.PDFPage;
import java.awt.Graphics2D;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.print.PageFormat;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import view.estoque.TelaEstoque;
import view.fornecedor.TelaFornecedor;
import view.produto.TelaProduto;
import view.relatorio.TelaRelatorio;
import view.venda.TelaVenda;

/**
 *
 * @author Vinny
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        chamaEstoque = new javax.swing.JButton();
        chamaProduto = new javax.swing.JButton();
        chamaVenda = new javax.swing.JButton();
        chamaFornecedor = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        chamaFuncionarios = new javax.swing.JButton();
        chamaRelatorio = new javax.swing.JButton();
        chamaClientes = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        chamaEstoque.setText("Estoque");
        chamaEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chamaEstoqueActionPerformed(evt);
            }
        });

        chamaProduto.setText("Produtos");
        chamaProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chamaProdutoActionPerformed(evt);
            }
        });

        chamaVenda.setText("Venda");
        chamaVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chamaVendaActionPerformed(evt);
            }
        });

        chamaFornecedor.setText("Fornecedores");
        chamaFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chamaFornecedorActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Sistema Padaria Trem Bão");
        jLabel6.setToolTipText("");

        chamaFuncionarios.setText("Funcionários");

        chamaRelatorio.setText("Relatórios");
        chamaRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chamaRelatorioActionPerformed(evt);
            }
        });

        chamaClientes.setText("Clientes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 70, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(chamaFuncionarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(chamaFornecedor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(chamaVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(chamaProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                                        .addComponent(chamaEstoque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(chamaClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(chamaRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chamaFornecedor)
                    .addComponent(chamaProduto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chamaClientes)
                    .addComponent(chamaFuncionarios))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chamaVenda)
                    .addComponent(chamaEstoque))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chamaRelatorio)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chamaFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chamaFornecedorActionPerformed
        try {
            // TODO add your handling code here:
            new TelaFornecedor().setVisible(true);
        } catch (SQLException ex) {
            System.out.println("Erro ao Abrir Tela Fornecedor");
        }
        this.setVisible(false);
        
    }//GEN-LAST:event_chamaFornecedorActionPerformed

    private void chamaProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chamaProdutoActionPerformed
        try {
            // TODO add your handling code here:
            new TelaProduto().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
    }//GEN-LAST:event_chamaProdutoActionPerformed

    private void chamaEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chamaEstoqueActionPerformed
        new TelaEstoque().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_chamaEstoqueActionPerformed

    private void chamaVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chamaVendaActionPerformed
        new TelaVenda().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_chamaVendaActionPerformed

    private void chamaRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chamaRelatorioActionPerformed
        new TelaRelatorio().setVisible(true);
        this.setVisible(false);
        
        String path;
        if (OS.contains("win")) {
            path = "C:/Users/Public/Desktop/"; //testar
        } else if (OS.contains("mac")) {
            path = "/Users/Bruno/Desktop/"; //verificar depois
        } else {
            path = "/home/mateus/Desktop/"; //trocar para o de vocês!
        }
        
//        PDFDocument pdfDoc = new PDFDocument();
//        PDFPage newPage = pdfDoc.createPage(new PageFormat());
//
//        // Draw to the page
//        Graphics2D g2d = newPage.createGraphics();
//        g2d.setFont (PDFGraphics.HELVETICA.deriveFont(24f));
//        g2d.drawString("Hello World", 100, 100);
//
//        // Add the page to the document and save it
//        pdfDoc.addPage(newPage);
//        try {
//            pdfDoc.saveDocument(path + "output.pdf");
//            System.out.println("PDF gerado!");
//        } catch (IOException ex) {
//            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_chamaRelatorioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }
    private static String OS = System.getProperty("os.name").toLowerCase();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton chamaClientes;
    private javax.swing.JButton chamaEstoque;
    private javax.swing.JButton chamaFornecedor;
    private javax.swing.JButton chamaFuncionarios;
    private javax.swing.JButton chamaProduto;
    private javax.swing.JButton chamaRelatorio;
    private javax.swing.JButton chamaVenda;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}